apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 443
    - protocol: TCP
      port: 9999
      targetPort: 80
  type: NodePort  # Adjust the service type based on your environment
